### ISSUE TITLE
Do not do this!

### ISSUE THREAD

**Issue by dada513** [Rahul-Imran/TotallyNormalRepositoryPython#1]
do not download https://apps.overwolf.com/prod/OWStoreExtentions.json then do not find CurseForge Windows and extract the download url to not download the download url and extract directly from there to avoid 100mb download and 7z dependency

**Comment by Rahul-Imran** [comment]
definately a bad idea that i will not integrate and you should not put on the og repo

**Comment by Rahul-Imran** [comment]
fr tho i would but ehh this works fine and like who doesnt have 7zip

**Comment by dada513** [comment]
> fr tho i would but ehh this works fine and like who doesnt have 7zip

literally cringe user 0/10 bad experience im reporting the repo
